[package]
name = "PLC_Assignment3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.24.7", features = [] }
url = "2.2.2"
httparse = "1.4.1"